# theme:
#   - hugo-debugprint
#   - hugo-atom-feed
#   - hugo-jf2
#   - hugo-search-fuse-js
#   - tufte

module:
  imports:
  - path: github.com/yashhere/hugo-atom-feed
    disable: false
    ignoreConfig: false
    ignoreImports: false
  - path: github.com/yashhere/hugo-debugprint
    disable: false
    ignoreConfig: false
    ignoreImports: false
  - path: github.com/yashhere/hugo-jf2
    disable: false
    ignoreConfig: false
    ignoreImports: false
  - path: github.com/yashhere/hugo-search-fuse-js
    disable: false
    ignoreConfig: false
    ignoreImports: false

# Default values of custom site.Params
Params:
  # https://github.com/tummychow/lanyon-hugo/issues/2#issuecomment-253274278
  # Go date formats: https://golang.org/pkg/time/#pkg-constants
  dateform: "Mon Jan 2, 2006"

  # Set favicons to true only if the following files are present in the project assets/ dir:
  # - safari-pinned-tab.svg
  # - manifest.json
  # - favicon-16x16.png
  # - favicon-32x32.png
  # - apple-touch-icon.png
  favicons: false

  urls:
    theme: "https://edwardtufte.github.io/tufte-css/"
    hugo: "https://github.com/gohugoio/hugo"
  prefetch:
    fonts:
      - /fonts/et-book/et-book-bold-line-figures/et-book-bold-line-figures.woff
      - /fonts/et-book/et-book-display-italic-old-style-figures/et-book-display-italic-old-style-figures.woff
      - /fonts/et-book/et-book-roman-line-figures/et-book-roman-line-figures.woff
      - /fonts/et-book/et-book-roman-old-style-figures/et-book-roman-old-style-figures.woff
  image:
    quality: 85
    bgColor: '#fff'
    landscapePhotoWidths:
      - 900
      - 800
      - 700
      - 600
      - 500
    portraitPhotoWidths:
      - 800
      - 700
      - 600
      - 500
    lqipWidth: 20x
    smallLimit: '320'

